# Generated by Django 6.0 on 2026-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match_punten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummerSpeler', models.IntegerField(default=1)),
                ('punten', models.IntegerField(default=0)),
                ('matchCode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='speler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=25)),
                ('voornaam', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
