# Generated by Django 6.0 on 2026-01-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_alter_match_punten_nummerspeler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_punten',
            name='nummerSpeler',
            field=models.IntegerField(default=1),
        ),
    ]
